### ISSUE TITLE
Erro ao doar livro.

### ISSUE THREAD

**Issue by raffacabofrio** [SharebookBR/sharebook-mobile#16]
Hoje a usuária Renata tentou doar um livro mas não conseguiu. Ela reclamou que deu erro.

Orientei ela a usar o web e ela conseguiu. Cliente atendida.

Fiz uma verificação e deu erro pra mim também. Segue evidência em anexo.

**Comment by maxgomes92** [comment]
Foi identificado que o problema está no token. Necessário verificar se ele ainda está válido sempre que abrir o app.
@raffacabofrio  saberia dizer se tem alguma forma de renovar o token? Ou seria melhor deslogar o usuário? Eu votaria na primeira opção.

**Comment by raffacabofrio** [comment]
Salve @maxgomes92. Hoje não temos um fluxo de renovação de token. Por enquanto a solução a curto prazo eh deslogar o usuário mesmo. :/

**Comment by maxgomes92** [comment]
Implementei a verificação da validade do token toda vez que abrir o app.
Logo abro a PR junto com a adição do one signal pra push notification.
